// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHAB9iHszQ3bMoOFmUfuUfwkjLQS4YEHo',
    appId: '1:28850550544:web:a65c67c72292ca3f7b5795',
    messagingSenderId: '28850550544',
    projectId: 'mango-app-c7bee',
    authDomain: 'mango-app-c7bee.firebaseapp.com',
    storageBucket: 'mango-app-c7bee.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCupk6GNQ6AOvpebp8iISu_Bl8cnCyKgP4',
    appId: '1:28850550544:android:6a85aa3bb6c6fd027b5795',
    messagingSenderId: '28850550544',
    projectId: 'mango-app-c7bee',
    storageBucket: 'mango-app-c7bee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3XniLpAsF-mVVYcbGKdxKAtRSV5-lrxA',
    appId: '1:28850550544:ios:b1d1c74a693ecfdd7b5795',
    messagingSenderId: '28850550544',
    projectId: 'mango-app-c7bee',
    storageBucket: 'mango-app-c7bee.firebasestorage.app',
    iosBundleId: 'com.example.mango',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3XniLpAsF-mVVYcbGKdxKAtRSV5-lrxA',
    appId: '1:28850550544:ios:b1d1c74a693ecfdd7b5795',
    messagingSenderId: '28850550544',
    projectId: 'mango-app-c7bee',
    storageBucket: 'mango-app-c7bee.firebasestorage.app',
    iosBundleId: 'com.example.mango',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHAB9iHszQ3bMoOFmUfuUfwkjLQS4YEHo',
    appId: '1:28850550544:web:cb0568957376e5c77b5795',
    messagingSenderId: '28850550544',
    projectId: 'mango-app-c7bee',
    authDomain: 'mango-app-c7bee.firebaseapp.com',
    storageBucket: 'mango-app-c7bee.firebasestorage.app',
  );
}
